#!/usr/bin/env python3
"""Build the by-module views of the list from the READMEs.

README.md / README.zh-CN.md are the source of truth for entry text and are
sorted by what the reader wants. by-module.md / by-module.zh-CN.md list the
same entries sorted by technical layer; which section each entry lands in
is set in scripts/by-module.json.

Usage:
    python3 scripts/build-by-module.py          # regenerate both files
    python3 scripts/build-by-module.py --check  # fail if out of date
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONFIG = ROOT / "scripts" / "by-module.json"

LANGS = {
    "en": {
        "readme": "README.md",
        "out": "by-module.md",
        "skip": {"Contents", "Related Lists", "Featured Badge"},
        "title": "Awesome AI Companion · By Building Block",
        "intro": (
            "The same entries as the [main list](README.md), sorted by technical layer "
            "for people assembling their own stack. "
            "If you would rather browse by what you want your companion to do, "
            "go back to the [main list](README.md)."
        ),
        "other": "[中文版](by-module.zh-CN.md)",
        "contents": "Contents",
        "legend": ("**Status:**", "**Platform:**"),
        "generated": (
            "<!-- Generated by scripts/build-by-module.py from README.md and "
            "scripts/by-module.json. Do not edit by hand. -->"
        ),
    },
    "zh": {
        "readme": "README.zh-CN.md",
        "out": "by-module.zh-CN.md",
        "skip": {"目录", "相关列表", "已收录徽章"},
        "title": "Awesome AI Companion · 按技术模块分类",
        "intro": (
            "与[主列表](README.zh-CN.md)收录的条目完全相同，按技术模块重新分类，"
            "适合自己搭系统的人查找。"
            "想按「想让 TA 做到什么」找，请回到[主列表](README.zh-CN.md)。"
        ),
        "other": "[English](by-module.md)",
        "contents": "目录",
        "legend": ("**状态:**", "**平台:**"),
        "generated": (
            "<!-- 由 scripts/build-by-module.py 根据 README.zh-CN.md 与 "
            "scripts/by-module.json 生成，请勿手动编辑。 -->"
        ),
    },
}

LINK_RE = re.compile(r"\]\(([^)]+)\)")


def key(url):
    return url.removeprefix("https://github.com/")


def anchor(title):
    """GitHub-style heading anchor."""
    s = re.sub(r"[^\w\- ]", "", title.strip().lower())
    return s.replace(" ", "-")


def read_entries(readme, skip):
    """Return {key: line} for list entries outside the skipped sections."""
    entries = {}
    section = None
    for line in (ROOT / readme).read_text(encoding="utf-8").splitlines():
        if line.startswith("## "):
            section = line[3:].strip()
        elif line.startswith("- [") and section not in skip:
            k = key(LINK_RE.search(line).group(1))
            if k in entries:
                sys.exit(f"{readme}: duplicate entry {k}")
            entries[k] = line
    return entries


def read_legend(readme, prefixes):
    lines = (ROOT / readme).read_text(encoding="utf-8").splitlines()
    return [next(l for l in lines if l.startswith(p)) for p in prefixes]


def groups_of(section):
    if "groups" in section:
        return section["groups"]
    return [{"title": None, "entries": section["entries"]}]


def check_mapping(config, entries, readme):
    mapped = [k for s in config["sections"] for g in groups_of(s) for k in g["entries"]]
    errors = []
    dup = sorted({k for k in mapped if mapped.count(k) > 1})
    if dup:
        errors.append(f"listed more than once in scripts/by-module.json: {', '.join(dup)}")
    unmapped = [k for k in entries if k not in mapped]
    if unmapped:
        errors.append(
            f"in {readme} but missing from scripts/by-module.json: {', '.join(unmapped)}"
        )
    stale = [k for k in mapped if k not in entries]
    if stale:
        errors.append(
            f"in scripts/by-module.json but not in {readme}: {', '.join(stale)}"
        )
    return errors


def render(lang, config, entries):
    L = LANGS[lang]
    out = [
        L["generated"],
        "",
        f"# {L['title']}",
        "",
        L["other"],
        "",
        L["intro"],
        "",
        *[x for l in read_legend(L["readme"], L["legend"]) for x in (l, "")],
        "---",
        "",
        f"## {L['contents']}",
        "",
    ]
    for s in config["sections"]:
        t = s["title"][lang]
        out.append(f"- [{t}](#{anchor(t)})")
    out += ["", "---", ""]
    for s in config["sections"]:
        out += [f"## {s['title'][lang]}", "", s["desc"][lang], ""]
        for g in groups_of(s):
            if g["title"]:
                out += [f"### {g['title'][lang]}", ""]
            out += [entries[k] for k in g["entries"]]
            out.append("")
        out += ["---", ""]
    return "\n".join(out[:-2]) + "\n"


def main():
    check = "--check" in sys.argv[1:]
    config = json.loads(CONFIG.read_text(encoding="utf-8"))
    errors = []
    for lang, L in LANGS.items():
        entries = read_entries(L["readme"], L["skip"])
        mapping_errors = check_mapping(config, entries, L["readme"])
        if mapping_errors:
            errors += mapping_errors
            continue
        text = render(lang, config, entries)
        path = ROOT / L["out"]
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                errors.append(
                    f"{L['out']} is out of date; run python3 scripts/build-by-module.py"
                )
        else:
            path.write_text(text, encoding="utf-8")
            print(f"wrote {L['out']}")
    if errors:
        sys.exit("\n".join(errors))


if __name__ == "__main__":
    main()
